DROP TABLE IF EXISTS ACCOUNT;

CREATE TABLE ACCOUNT (
    ACC_ID LONG PRIMARY KEY AUTO_INCREMENT NOT NULL,
    ACC_EMAIL VARCHAR2(50),
    ACC_BALANCE DECIMAL(20,2)
);

CREATE UNIQUE INDEX ACC_IDX_UQ on ACCOUNT(ACC_EMAIL);